version: '3.8'

services:
  tp-devops:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_VERSION=1.0.0  
    image: gonza/tp-devops:latest  
    container_name: book-service
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - SENTRY_DSN=  
      - PORT=5000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:$PORT/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    volumes:
      - ./src:/app/src  
    networks:
      - book-network

  test-runner:
    image: gonza/tp-devops:latest
    container_name: test-container
    command: ["pytest", "tests/", "-v"]
    depends_on:
      tp-devops:
        condition: service_healthy
    networks:
      - book-network

networks:
  book-network:
    driver: bridge