version: '3.8'

services:
  tp-devops:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_VERSION=1.0.0  # Versión específica
    image: gonza/tp-devops:latest  # Tag específico
    container_name: book-service
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - book-network

  # Servicio opcional para ejecutar pruebas (ejecutar manualmente)
  test-runner:
    build:
      context: .
      dockerfile: Dockerfile
    image: tp-devops:compose
    container_name: test-container
    command: ["pytest", "test_app.py", "-v"]
    depends_on:
      tp-devops:
        condition: service_healthy
    networks:
      - book-network

networks:
  book-network:
    driver: bridge